In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/heart-attack-analysis-prediction-dataset/o2Saturation.csv
/kaggle/input/heart-attack-analysis-prediction-dataset/heart.csv


In [2]:
df = pd.read_csv('/kaggle/input/heart-attack-analysis-prediction-dataset/heart.csv')



In [3]:
df['output'].value_counts()

1    165
0    138
Name: output, dtype: int64

In [4]:
df['age'].describe()

count    303.000000
mean      54.366337
std        9.082101
min       29.000000
25%       47.500000
50%       55.000000
75%       61.000000
max       77.000000
Name: age, dtype: float64

In [5]:
columns = ['sex','cp','fbs','restecg','exng','slp','caa','thall','output']

In [6]:
k  = [x for x in df.columns if x not in columns ]
tmp2= df[k]
tmp2


age  trtbps  chol  thalachh  oldpeak
0     63     145   233       150      2.3
1     37     130   250       187      3.5
2     41     130   204       172      1.4
3     56     120   236       178      0.8
4     57     120   354       163      0.6
..   ...     ...   ...       ...      ...
298   57     140   241       123      0.2
299   45     110   264       132      1.2
300   68     144   193       141      3.4
301   57     130   131       115      1.2
302   57     130   236       174      0.0

[303 rows x 5 columns]

In [7]:

tmp = df[columns].astype("category")
tmp

sex cp fbs restecg exng slp caa thall output
0     1  3   1       0    0   0   0     1      1
1     1  2   0       1    0   0   0     2      1
2     0  1   0       0    0   2   0     2      1
3     1  1   0       1    0   2   0     2      1
4     0  0   0       1    1   2   0     2      1
..   .. ..  ..     ...  ...  ..  ..   ...    ...
298   0  0   0       1    1   1   0     3      0
299   1  3   0       1    0   1   0     3      0
300   1  0   1       1    0   1   2     3      0
301   1  0   0       1    1   1   1     3      0
302   0  1   0       0    0   1   1     2      0

[303 rows x 9 columns]

In [8]:
df_final = pd.concat([tmp,tmp2],axis=1)
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype   
---  ------    --------------  -----   
 0   sex       303 non-null    category
 1   cp        303 non-null    category
 2   fbs       303 non-null    category
 3   restecg   303 non-null    category
 4   exng      303 non-null    category
 5   slp       303 non-null    category
 6   caa       303 non-null    category
 7   thall     303 non-null    category
 8   output    303 non-null    category
 9   age       303 non-null    int64   
 10  trtbps    303 non-null    int64   
 11  chol      303 non-null    int64   
 12  thalachh  303 non-null    int64   
 13  oldpeak   303 non-null    float64 
dtypes: category(9), float64(1), int64(4)
memory usage: 16.0 KB


In [9]:
y = df.output
X = df.drop('output',axis=1)

In [10]:
#test train split
import numpy as np
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [20]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
LR = LogisticRegression()
DTC = DecisionTreeClassifier()
RFC = RandomForestClassifier()
GBC = GradientBoostingClassifier()
SVC = SVC()
from sklearn.metrics import *

In [12]:
lr = LR.fit(X_train,y_train)
y_pred = lr.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.86      0.88        29
           1       0.88      0.91      0.89        32

    accuracy                           0.89        61
   macro avg       0.89      0.88      0.88        61
weighted avg       0.89      0.89      0.89        61

[[25  4]
 [ 3 29]]


/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [13]:
gbc = GBC.fit(X_train,y_train)
y_pred = gbc.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.74      0.79      0.77        29
           1       0.80      0.75      0.77        32

    accuracy                           0.77        61
   macro avg       0.77      0.77      0.77        61
weighted avg       0.77      0.77      0.77        61

[[23  6]
 [ 8 24]]


In [14]:
rfc = RFC.fit(X_train,y_train)
y_pred = rfc.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.83      0.84        29
           1       0.85      0.88      0.86        32

    accuracy                           0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61

[[24  5]
 [ 4 28]]


In [15]:
svc = SVC.fit(X_train,y_train)
y_pred = svc.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.52      0.62        29
           1       0.67      0.88      0.76        32

    accuracy                           0.70        61
   macro avg       0.73      0.70      0.69        61
weighted avg       0.73      0.70      0.69        61

[[15 14]
 [ 4 28]]


In [31]:
params_SVC = {'C': [1,2], 'kernel': ['linear', 'poly'], 'gamma':['scale'], 'tol':[1e-3,1e-2,1e-1],'probability':[True] }
params_gbc = {'loss':['log_loss', 'exponential'],'learning_rate':[0.1,0.2,0.01,0.05]}
params = {SVC:(params_SVC),GBC:(params_gbc)}


In [32]:
for i,j in params.items(): 
    print(i,j)
    clf = GridSearchCV(estimator=i, param_grid=j)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    y_prob = np.max(clf.predict_proba(X_test), axis=1)
    print('model_accuracy:',clf.best_score_)
    print('roc_auc_score:',roc_auc_score(y_test,y_prob))    
    print(r'confusion_matrix:',confusion_matrix(y_pred,y_test))
    print('precision_score:',precision_score(y_pred,y_test))
    print('Recall_score:',recall_score(y_pred,y_test))
    print(classification_report(y_test, y_pred))
    print('BEST PARAMETERS:{}'.format(clf.best_params_))

SVC() {'C': [1, 2], 'kernel': ['linear', 'poly'], 'gamma': ['scale'], 'tol': [0.001, 0.01, 0.1], 'probability': [True]}
model_accuracy: 0.8180272108843537
roc_auc_score: 0.25969827586206895
confusion_matrix: [[26  4]
 [ 3 28]]
precision_score: 0.875
Recall_score: 0.9032258064516129
              precision    recall  f1-score   support

           0       0.87      0.90      0.88        29
           1       0.90      0.88      0.89        32

    accuracy                           0.89        61
   macro avg       0.88      0.89      0.89        61
weighted avg       0.89      0.89      0.89        61

BEST PARAMETERS:{'C': 2, 'gamma': 'scale', 'kernel': 'linear', 'probability': True, 'tol': 0.1}
GradientBoostingClassifier() {'loss': ['log_loss', 'exponential'], 'learning_rate': [0.1, 0.2, 0.01, 0.05]}
model_accuracy: 0.8056122448979591
roc_auc_score: 0.3372844827586207
confusion_matrix: [[23  8]
 [ 6 24]]
precision_score: 0.75
Recall_score: 0.8
              precision    recall  f1-sc

/opt/conda/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
20 fits failed out of a total of 40.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/ensemble/_gb.py", line 525, in fit
    self._check_params()
  File "/opt/conda/lib/python3.7/site-packages/sklearn/ensemble/_gb.py", line 282, in _check_params
    raise ValueError("Loss '{0:s}' not supported. ".format(self.loss))
ValueError: Loss 'log_loss' not 