<a href="https://colab.research.google.com/github/sindla97/Machine-Learning/blob/main/Bert_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
from transformers import TFBertTokenizer,BertTokenizerFast, TFBertModel, BertLayer


In [6]:
tokenize=TFBertTokenizer.from_pretrained('bert-large-cased')

In [8]:
encoded=tokenize(['Hemanth','is a asshole'])



In [9]:
model=TFBertModel.from_pretrained('bert-large-cased')

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [10]:
encoded

{'input_ids': <tf.Tensor: shape=(2, 5), dtype=int64, numpy=
 array([[  101,  1124,  1399,  1582,   102],
        [  101,  1110,   170, 27877,   102]])>,
 'attention_mask': <tf.Tensor: shape=(2, 5), dtype=int64, numpy=
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])>,
 'token_type_ids': <tf.Tensor: shape=(2, 5), dtype=int64, numpy=
 array([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])>}

In [13]:
model(encoded)

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(2, 5, 1024), dtype=float32, numpy=
array([[[-0.7410247 , -0.08453304,  0.3512593 , ..., -0.03892468,
         -0.6113131 ,  0.13222834],
        [-0.5081473 , -1.0046306 , -0.09670912, ..., -0.5713471 ,
          0.25065717, -0.39655128],
        [-0.13297059,  0.04868938,  0.32917523, ..., -0.11524402,
         -0.14398642, -0.2851179 ],
        [-1.1150161 , -0.4759027 , -0.11566375, ...,  0.6752935 ,
          0.07073672,  0.13514736],
        [-0.61365634, -1.4850808 ,  0.38189974, ...,  0.5183874 ,
         -0.4681304 , -0.17568077]],

       [[-0.49310523, -0.21431933,  0.5574328 , ..., -0.35691494,
         -0.4983406 ,  0.09909564],
        [-0.50194514, -0.7799337 , -0.24431807, ..., -0.35499412,
         -0.00606415,  0.0461541 ],
        [ 0.16381828,  0.27361274,  0.07078988, ...,  0.6253388 ,
          0.12387747,  0.29849824],
        [ 0.19375493,  0.08191492,  0.04811272, ...,  0.703217 