In [1]:
import pandas as pd
import numpy as np


In [2]:
reviews_sample= pd.read_csv(r'C:\Users\shanm\OneDrive\Desktop\Machine-Learning\Data\Sephora_sample\X_reviews_sample.csv')
reviews_sample.head()

Unnamed: 0                                        review_text  label  \
0           0  This did nothing for my lips. It smells great ...    0.0   
1           1  I first tried the original formulation a coupl...    0.0   
2           2  Did absolutely nothing. Tried multiple times t...    0.0   
3           3  Feels nice, does nothing. Very disappointed wi...    0.0   
4           4  This is literally the best makeup remover. Doe...    1.0   

   rating  text_word_count                                         clean_text  \
0       2               24  this did nothing for my lips it smells great b...   
1       2               84  i first tried the original formulation a coupl...   
2       1               24  did absolutely nothing tried multiple times to...   
3       2               29  feels nice does nothing very disappointed with...   
4       5               12  this is literally the best makeup remover does...   

                                      tokenized_text  \
0  ['noth', 'lip', 'smell', 'great', 'make', 'lip...   
1  ['first', 'tri', 'origin', 'formul', 'coupl', ...   
2  ['absolut', 'noth', 'tri', 'multipl', 'time', ...   
3  ['feel', 'nice', 'noth', 'disappoint', 'super'...   
4  ['liter', 'best', 'makeup', 'remov', '’', 'giv...   

                                    tokenized_text_2  
0  noth lip smell great make lip smoother use two...  
1  first tri origin formul coupl time sampl fell ...  
2  absolut noth tri multipl time give chanc anyth...  
3  feel nice noth disappoint super expens water f...  
4                 liter best makeup remov ’ give acn

In [3]:
X= reviews_sample['tokenized_text_2']
y = reviews_sample['label'] 

In [4]:
from sklearn.model_selection import train_test_split

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.80)

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() # encoding
y_train_label= le.fit_transform(y_train)
y_test_label= le.transform(y_test)

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer
vec = TfidfVectorizer(stop_words="english", analyzer='word', 
                            ngram_range=(1, 1), max_df=1.0, min_df=1, max_features=15000)
vec.fit(X_train)
x_train=vec.transform(X_train)
x_test=vec.transform(X_test)

In [7]:
vec.transform(['happi hear work other hand oili complexion']).toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [23]:
vec.get_feature_names_out()

array(['aa', 'aaaaahmaz', 'aaaaamaz', ..., 'été', 'être', '좋다'],
      dtype=object)

In [9]:
 x_train = x_train.toarray()

In [10]:
x_train[25][:-2]

array([0., 0., 0., ..., 0., 0., 0.])

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
model = Sequential()
model.add(Dense(50, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(25, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 50)                750050    
                                                                 
 dense_1 (Dense)             (None, 25)                1275      
                                                                 
 dense_2 (Dense)             (None, 1)                 26        
                                                                 
Total params: 751,351
Trainable params: 751,351
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.fit(x_train,y_train_label,epochs=10,steps_per_epoch=10)

Epoch 1/10
10/10 [==============================] - 2s 78ms/step - loss: 0.6867 - accuracy: 0.7135
Epoch 2/10
10/10 [==============================] - 1s 74ms/step - loss: 0.6566 - accuracy: 0.8128
Epoch 3/10
10/10 [==============================] - 1s 74ms/step - loss: 0.6115 - accuracy: 0.8368
Epoch 4/10
10/10 [==============================] - 1s 72ms/step - loss: 0.5541 - accuracy: 0.8482
Epoch 5/10
10/10 [==============================] - 1s 76ms/step - loss: 0.4897 - accuracy: 0.8635
Epoch 6/10
10/10 [==============================] - 1s 75ms/step - loss: 0.4266 - accuracy: 0.8722
Epoch 7/10
10/10 [==============================] - 1s 74ms/step - loss: 0.3720 - accuracy: 0.8805
Epoch 8/10
10/10 [==============================] - 1s 74ms/step - loss: 0.3296 - accuracy: 0.8874
Epoch 9/10
10/10 [==============================] - 1s 76ms/step - loss: 0.2985 - accuracy: 0.8937
Epoch 10/10
10/10 [==============================] - 1s 66ms/step - loss: 0.2758 - accuracy: 0.9000


In [24]:
model.predict(vec.transform(['happi hear work other hand oili complexion']).toarray())

array([[0.39144894]], dtype=float32)