In [1]:
import pandas as pd
import numpy as np


In [3]:
reviews_sample= pd.read_csv(r'C:\Users\shanm\OneDrive\Desktop\Git_data\Sephora_sample\X_reviews_sample.csv',low_memory =True)
reviews_sample.head()

Unnamed: 0                                        review_text  label  \
0           0  Gel type moisturizers aren’t typically my go-t...    1.0   
1           1  smells great! works really well on my acne sca...    1.0   
2           2  Caused me so many breakouts. I thought this wo...    0.0   
3           3  I could not be happier with this mask! I alway...    1.0   
4           4  Fastest acting spot reducer I have ever tried....    1.0   

   rating  text_word_count                                         clean_text  \
0       5               51  gel type moisturizers aren’t typically my goto...   
1       4               44  smells great works really well on my acne scar...   
2       1               29  caused me so many breakouts i thought this wou...   
3       5               45  i could not be happier with this mask i always...   
4       5               50  fastest acting spot reducer i have ever tried ...   

                                      tokenized_text  \
0  ['gel', 'type', 'moistur', '’', 'typic', 'goto...   
1  ['smell', 'great', 'work', 'realli', 'well', '...   
2  ['caus', 'mani', 'breakout', 'thought', 'would...   
3  ['could', 'happier', 'mask', 'alway', 'use', '...   
4  ['fastest', 'act', 'spot', 'reduc', 'ever', 't...   

                                    tokenized_text_2  
0  gel type moistur ’ typic goto one impress gel ...  
1  smell great work realli well acn scare need co...  
2  caus mani breakout thought would good use clea...  
3  could happier mask alway use overnight mask am...  
4  fastest act spot reduc ever tri got watch one ...

In [4]:
X= reviews_sample['tokenized_text_2']
y = reviews_sample['label'] 

In [5]:
from sklearn.model_selection import train_test_split

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.80)

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() # encoding
y_train_label= le.fit_transform(y_train)
y_test_label= le.transform(y_test)

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
vec = TfidfVectorizer(stop_words="english", analyzer='word', 
                            ngram_range=(1, 1), max_df=1.0, min_df=1, max_features=15000)
vec.fit(X_train)
x_train=vec.transform(X_train)
x_test=vec.transform(X_test)

In [13]:
print(vec.transform(['happi hear work other hand oili complexion']).toarray()[0][0:-10])

[0. 0. 0. ... 0. 0. 0.]


In [14]:
vec.get_feature_names_out()

array(['aa', 'aaaaag', 'aaaaahmaz', ..., 'ꜰʀᴏᴍ', 'ꜰᴀʟʟꜰᴀᴠᴇꜱᴠᴏxʙᴏx', 'ꜰᴏʀ'],
      dtype=object)

In [15]:
 x_train = x_train.toarray()

In [16]:
x_train[25][:-2]

array([0., 0., 0., ..., 0., 0., 0.])

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
model = Sequential()
model.add(Dense(50, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(25, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 50)                750050    
                                                                 
 dense_1 (Dense)             (None, 25)                1275      
                                                                 
 dense_2 (Dense)             (None, 1)                 26        
                                                                 
Total params: 751,351
Trainable params: 751,351
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.fit(x_train,y_train_label,epochs=10,steps_per_epoch=10)

Epoch 1/10
10/10 [==============================] - 2s 78ms/step - loss: 0.6867 - accuracy: 0.7135
Epoch 2/10
10/10 [==============================] - 1s 74ms/step - loss: 0.6566 - accuracy: 0.8128
Epoch 3/10
10/10 [==============================] - 1s 74ms/step - loss: 0.6115 - accuracy: 0.8368
Epoch 4/10
10/10 [==============================] - 1s 72ms/step - loss: 0.5541 - accuracy: 0.8482
Epoch 5/10
10/10 [==============================] - 1s 76ms/step - loss: 0.4897 - accuracy: 0.8635
Epoch 6/10
10/10 [==============================] - 1s 75ms/step - loss: 0.4266 - accuracy: 0.8722
Epoch 7/10
10/10 [==============================] - 1s 74ms/step - loss: 0.3720 - accuracy: 0.8805
Epoch 8/10
10/10 [==============================] - 1s 74ms/step - loss: 0.3296 - accuracy: 0.8874
Epoch 9/10
10/10 [==============================] - 1s 76ms/step - loss: 0.2985 - accuracy: 0.8937
Epoch 10/10
10/10 [==============================] - 1s 66ms/step - loss: 0.2758 - accuracy: 0.9000


In [24]:
model.predict(vec.transform(['happi hear work other hand oili complexion']).toarray())

array([[0.39144894]], dtype=float32)