<a href="https://colab.research.google.com/github/sindla97/Machine-Learning/blob/main/text_classification_imdb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Objective: Text_claasifiacation using distilBERT on IMDB data (50k rows)

1.   Baseline accuracy: LSTM
2.   DistillBERT





In [1]:
#importing library
import pandas as pd
import numpy as np
import tensorflow as tf


In [2]:
#!pip install opendatasets

import opendatasets as od

od.download(
	"https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews/data")


Skipping, found downloaded files in "./imdb-dataset-of-50k-movie-reviews" (use force=True to force download)


In [3]:

# reading the XLSX file
file =('/content/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv')
imdb = pd.read_csv(file)



In [25]:

imdb.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train,X_test,y_train,y_test=train_test_split(imdb.review,imdb.sentiment,test_size=0.5)

In [4]:
from transformers import  AutoTokenizer, TFAutoModel

In [5]:
tokenizer=AutoTokenizer.from_pretrained('distilbert-base-uncased')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


In [6]:
model= TFAutoModel.from_pretrained('distilbert-base-uncased')

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFDistilBertModel: ['vocab_projector.bias', 'vocab_layer_norm.weight', 'vocab_transform.bias', 'vocab_layer_norm.bias', 'vocab_transform.weight']
- This IS expected if you are initializing TFDistilBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFDistilBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


In [7]:
def tokenize(example):
  return tokenizer(example, max_length=500,padding='max_length',truncation=True,return_tensors='tf')

In [8]:
encoded_dict=tokenize([x for x in imdb.review])

In [9]:
imdb.review[0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [10]:
encoded_dict

{'input_ids': <tf.Tensor: shape=(5, 500), dtype=int32, numpy=
array([[  101,  2028,  1997, ...,     0,     0,     0],
       [  101,  1037,  6919, ...,     0,     0,     0],
       [  101,  1045,  2245, ...,     0,     0,     0],
       [  101, 10468,  2045, ...,     0,     0,     0],
       [  101,  9004,  3334, ...,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(5, 500), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>}

In [ ]:
tokenizer.convert_ids_to_tokens(encoded_dict['input_ids'][0])

In [ ]:
max([len(x.split()) for x in imdb.review ])

In [12]:
embeddings=model(encoded_dict['input_ids'],encoded_dict['attention_mask'],output)

In [32]:
embeddings[:][:][0]

<tf.Tensor: shape=(5, 500, 768), dtype=float32, numpy=
array([[[ 0.06994878, -0.31668684,  0.01708935, ..., -0.006975  ,
          0.5686798 ,  0.22723992],
        [-0.40850887, -0.21310097, -0.0715927 , ...,  0.18035556,
          0.3012867 ,  0.2836612 ],
        [-0.7219142 , -0.10970731, -0.22000517, ...,  0.18461503,
          0.1966958 ,  0.10151203],
        ...,
        [ 0.24309279,  0.17713022,  0.00771184, ..., -0.27585173,
         -0.11715513, -0.39013603],
        [ 0.37102437,  0.01719925,  0.28849587, ..., -0.21588287,
          0.01631809, -0.4274383 ],
        [ 0.51339835,  0.13813677,  0.26624948, ..., -0.14217937,
          0.00740017, -0.3375818 ]],

       [[-0.11449713, -0.14964448,  0.13823557, ..., -0.02278855,
          0.32166734,  0.30705848],
        [-0.3225921 , -0.25530645,  0.36998475, ...,  0.06877449,
          0.656541  ,  0.42610446],
        [ 0.38216928,  0.11269273,  0.58734995, ..., -0.05023529,
          0.27519673, -0.15334633],
        ...,